### ISSUE TITLE
3章の「rails test」でエラーメッセージが表示される件

### ISSUE THREAD

**Issue by piyoppi** [piyoppi/rails_tutorial_chap3_study#1]
# 概要
- Rails チュートリアルの「テスト」を実行
    - https://railstutorial.jp/chapters/static_pages?version=5.0#sec-our_first_test
- コマンドを実行すると以下のように表示される
```
$ rails test
Running via Spring preloader in process 35465
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/usr/local/lib/ruby/gems/2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/Users/xxx.xxx/prog/rails_tutorial_chap3_study/db/schema.rb doesn't exist yet. Run `rails db:migrate` to create it, then try again. If you do not intend to use a database, you should instead alter /Users/xxx.xxx/prog/rails_tutorial_chap3_study/config/application.rb to limit the frameworks that will be loaded.
Run options: --seed 37138

# Running:

..

Finished in 0.647025s, 3.0911 runs/s, 3.0911 assertions/s.
/usr/local/lib/ruby/gems/2.4.0/gems/railties-5.0.1/lib/rails/test_unit/minitest_plugin.rb:9:in `aggregated_results': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:597:in `report'
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-reporters-1.1.9/lib/minitest/minitest_reporter_plugin.rb:26:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-reporters-1.1.9/lib/minitest/minitest_reporter_plugin.rb:26:in `report'
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `each'
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:687:in `report'
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:141:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/railties-5.0.1/lib/rails/test_unit/minitest_plugin.rb:73:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/minitest-5.10.2/lib/minitest.rb:63:in `block in autorun'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'
        from /usr/local/lib/ruby/gems/2.4.0/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'
        from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

**Comment by piyoppi** [comment]
## 原因
- Rails のバグであることが言及されているっぽい
    - https://github.com/seattlerb/minitest/issues/689
    - https://github.com/rails/rails/pull/29022

**Comment by piyoppi** [comment]
## 原因   
- Railsのバグであるっぽい。すでにFixされている
    - https://github.com/rails/rails/pull/29022

**Comment by piyoppi** [comment]
## 解決策
- バグのFixは 5.0.3 で反映されているっぽいので、Gemfileを以下のように修正
```rb
gem 'rails',        '5.0.3'
```
